apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-datadog
  labels:
    byoc.speedscale.com/provider: datadog
data:
  otel.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 400
        spike_limit_mib: 80
      batch: {}
    exporters:
      datadog:
        api:
          site: {{ .Values.datadog.site | quote }}
          key: ${env:DD_API_KEY}
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    service:
      extensions: [health_check]
      pipelines:
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [datadog]
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [datadog]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [datadog]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-datadog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-datadog
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-datadog
        app.kubernetes.io/version: {{ .Chart.Version | quote }}
    spec:
      containers:
        - name: collector
          image: {{ .Values.image }}
          args: ["--config=/conf/otel.yaml"]
          env:
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.datadog.credentialsSecret }}
                  key: {{ .Values.datadog.apiKeyField }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - {name: grpc, containerPort: 4317}
            - {name: http, containerPort: 4318}
            - {name: health, containerPort: 13133}
          readinessProbe:
            httpGet: {path: /, port: health}
          livenessProbe:
            httpGet: {path: /, port: health}
          volumeMounts:
            - {name: config, mountPath: /conf, readOnly: true}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-datadog
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-datadog
spec:
  selector:
    app: {{ .Release.Name }}-datadog
  ports:
    - {name: grpc, port: 4317, targetPort: grpc}
    - {name: http, port: 4318, targetPort: http}
