apiVersion: v2
name: newrelic
description: Dedicated Speedscale BYOC channel for New Relic logs, traces, and metrics.
type: application
version: 1.1.0
appVersion: "0.160.0"
keywords: [speedscale, byoc, newrelic, opentelemetry]
home: https://github.com/speedscale/speedscale-byoc
maintainers:
  - name: Speedscale
    email: support@speedscale.com
