apiVersion: v2
name: datadog
description: Dedicated Speedscale BYOC channel for Datadog logs, traces, and metrics.
type: application
version: 1.2.0
appVersion: "0.160.0"
keywords: [speedscale, byoc, datadog, opentelemetry]
home: https://github.com/speedscale/speedscale-byoc
maintainers:
  - name: Speedscale
    email: support@speedscale.com
